version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
  processing:
    build:
      context: .
      dockerfile: ./processing/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__ProcessingDb: "Server=sqlserver,1433;Database=ProcessingDb;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True;"
      ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"
      LOKI_URL: "http://loki:3100"
      SEQ_URL: "http://seq:5341"
    depends_on:
      - sqlserver
      - zipkin
      - seq
      - loki
    ports:
      - "5000:80"
      - "9467:9464"
  ingestion:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ProcessingService__Url: "http://processing:80"
      ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"
      LOKI_URL: "http://loki:3100"
      SEQ_URL: "http://seq:5341"
    depends_on:
      - processing
      - zipkin
      - seq
      - loki
    ports:
      - "5002:80"
      - "9468:9464"
  
  dashboard:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__ProcessingDb: "Server=sqlserver,1433;Database=ProcessingDb;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True;"
      ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"
      LOKI_URL: "http://loki:3100"
      SEQ_URL: "http://seq:5341"
    depends_on:
      - sqlserver
      - zipkin
      - seq
      - loki
    ports:
      - "5004:80"
      - "9469:9464"
  seq:
    image: datalust/seq
    ports:
      - "5341:5341"
      - "5342:80"
    environment:
      SEQ_FIRSTRUN_ADMINPASSWORD: "password"
      ACCEPT_EULA: "Y"
    volumes:
      - rps_seq_data:/data
  zipkin:
    image: openzipkin/zipkin:3.4.1
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      - MYSQL_DB=zipkin
    depends_on:
      - zipkin-storage
  zipkin-storage:
    image: openzipkin/zipkin-mysql
    ports:
      - "3306:3306"
    volumes:
      - zipkin_data:/mysql/data
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - processing
      - ingestion
      - dashboard
  grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_USERS_ALLOW_SIGN_UP=false
      volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana-provisioning:/etc/grafana/provisioning
      depends_on:
        - seq
        - zipkin
        - prometheus
        - loki
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
volumes:
  sqlserver-data:
  rps_seq_data:
  zipkin_data:
  grafana_data:  
  loki_data:
  prometheus_data: