global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'processing'
    static_configs:
      - targets: ['processing:9464']
  
  - job_name: 'ingestion'
    static_configs:
      - targets: ['ingestion:9464']
  
  - job_name: 'dashboard'
    static_configs:
      - targets: ['dashboard:9464']